name: Playwright Tests and Publish Reports

on:
  push:
    branches: [main]  # Upewnij się, że to Twoja główna gałąź
  pull_request:
    branches: [main]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Upewnij się, że wersja Node.js jest zgodna z Twoim projektem

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: npx playwright test --reporter=html

      - name: Deploy report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-report
